### ISSUE TITLE
How to "hook" existing actions?

### ISSUE THREAD

**Issue by Demosthenexx** [nicm/fdm#104]
I'm trying to run "mu add $messagefile" every time I deliver a message to a maildir mailbox. I don't see a way to pass arguments to a custom action, or a way to hook onto the existing maildir action.

So while I could create a custom action to try to include maildir and exec, I cannot pass the maildir directory name to the action.

Ideally something like:

`action "mumaildir" actions { maildir $1 action exec "mu add %[mail_file]" }`
`match account "myaccount.com" action "mumaildir" "${mail}/Myaccount.com.Inbox"`

The closest way I have found is to create a custom action for mu add, and then call it after maildir has tagged the message on delivery.

`action "muadd" exec "mu add '%[mail_file]'"`
`match account "myaccount.com"   actions { maildir "${mail}/Myaccount.com.Inbox" action "muadd" }`

This works but feels awkward.

If I use this method, I'll have to expand all of my maildir actions to include the extra redundant code. Thus I'm asking if I missed something.

**Comment by nicm** [comment]
You could match at the end on the `mail_file` tag?

**Comment by nicm** [comment]
You will either need to do that or add your action to every maildir match.

**Comment by Demosthenexx** [comment]
Ok, thanks for confirming. I'll consider whether I can reflow my config to have a default action at the end. Thanks for fdm, and your unreasonably fast response. ;]

**Comment by Demosthenexx** [comment]
For future searchers, this was a futile approach anyway. It appears that mu4e locks the Xapian database while open, so you cannot run "mu index" or "mu add $messagefile". FDM was perfectly capable, but I had to remove the event driven mu add from my config and rely on mu4e's internal index run.
