### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by panosalevropoulos** [nicm/fdm#106]
[Wikipedia](https://en.wikipedia.org/wiki/Fdm_(software)) says that fdm is under the ISC license, but I can't find it. Is there a license? If yes, please add it.

**Comment by ninjin** [comment]
On Fri 25 Mar 2022, panosalevropoulos wrote:
> 
> [Wikipedia](https://en.wikipedia.org/wiki/Fdm_(software)) says that fdm is under the ISC license, but I can't find it. Is there a license? If yes, please add it.

From what I can tell, the ISC license is at the top of each header and source file. That should be about as explicit at it gets.

**Comment by panosalevropoulos** [comment]
That's great, I didn't notice. A COPYING/LICENSE file would make things even better.
