### ISSUE TITLE
new release with oauth2

### ISSUE THREAD

**Issue by pdobsan** [nicm/fdm#107]
@nicm, thanks for fdm, I have been using it for ages. In particular, the patch [905df31](https://github.com/nicm/fdm/commit/905df314bdee77d5125833fa672b2ad09e602303) for oauth2 works great with gmail. That is important, since google and many other email services make oauth2 mandatory recently.

Unfortunately, most distros provide only the released version of fdm so one is forced to build from sources. While that is fine with me it might deterrent many potential users.

Could you, please, release a new version of fdm as it is now? Perhaps with an example in documentation on how to use outh2 with gmail. Something like this:

    account "example@gmail.com" imaps server "imap.gmail.com"
        user "example@gmail.com"
        pass $(password-manager example)
        oauthbearer

Thank you!

**Comment by nicm** [comment]
Yes... I have been very busy but I will try to do it in a few weeks.

**Comment by sthen** [comment]
It may need the patch in https://github.com/nicm/fdm/issues/94#issuecomment-1059969559 or alternative first, there are some issues with non-zero exit codes on success with present git head code which are fixed by the patch in that comment

**Comment by nicm** [comment]
I have added a 2.1 release now, let me know of any problems.

**Comment by pdobsan** [comment]
That is great, thank you!

I have already requested a new Archlinux fdm package and will correct the Arch wiki entry on fdm.

**Comment by pdobsan** [comment]
On Wed, Jun 01, 2022 at 12:08:30AM -0700, Nicholas Marriott wrote:
> I have added a 2.1 release now, let me know of any problems.

That is great, thank you!

I have already requested a new Archlinux fdm package and will correct
the Arch wiki entry on fdm.
