### ISSUE TITLE
Locking of local system mailbox

### ISSUE THREAD

**Issue by stefankreutz** [nicm/fdm#112]
I would like to fetch mails from my local system mbox at `/var/mail/user` in addition to several IMAP servers to have them delivered to a single inbox maildir to be read by mutt. It appears to work with the following account settings:

```
account "localhost"
  mbox "/var/mail/user"

account "user@example.com"
  imaps ...
```

However, fdm doesn't appear to respect the lock file `/var/lock/user.lock` created by the system SMTP daemon, in my case OpenSMTPD. I've tried it with each of the available `lock-types`. With `flock` and `fcntl`, fdm ignores the lock file. With `dotlock`, fdm blocks in presence of the lock file (as expected), but doesn't continue when the lock file is removed. Instead, it hangs until killed and afterwards complains about wrong permissions of the mbox file, which I cannot observe.

I suppose that's the intended behavior and I'm not using fdm as intended, right? If so, is there anything I can do to get this working?

**Comment by stefankreutz** [comment]
I may have found a different way to fetch mail from the local system. I've added the following [`forward(5)`](https://man.openbsd.org/forward) rule to pipe mail to fdm:

```
"|/usr/local/bin/fdm -a stdin fetch"
```

And I've added the following account to receive this mail:

```
account "stdin" disabled stdin
```

Is that the correct way to use fdm? I'm still unsure whether fdm should have respected `/var/mail/user.lock`.

**Comment by nicm** [comment]
Piping in `.forward` is fine and is common.

fdm will ignore a `.lock` file with anything except `dotlock`, the other lock types are on the mbox itself.

I don't see where OpenSMTPd creates lock files, it looks to me like it uses flock.

**Comment by stefankreutz** [comment]
Hey, thanks for the confirmation. Works like a charm. :)
