### ISSUE TITLE
Consider new release for PCRE2 support

### ISSUE THREAD

**Issue by thesamesam** [nicm/fdm#121]
Hi,

Would it be possible to make a new release containing https://github.com/nicm/fdm/commit/136bf1e5aa1746af356f8c369ba39b27981925f3 for pcre2 support?

Distros are currently trying to get rid of libpcre1 given it's EOL so this would be one thing off the list.

Thanks!

**Comment by nicm** [comment]
Done now, thanks.

**Comment by thesamesam** [comment]
Thank you!
