### ISSUE TITLE
Certificate verification is disabled by default

### ISSUE THREAD

**Issue by avkrotov** [nicm/fdm#14]
Unless user adds "set verify-certificates", certificates are not checked at all. As fdm tries to be secure by default (for example, it checks file permissions), it would be good to always enable certificate verification. If certificate verification is not needed, it can be disabled with "no-verify" keyword. Otherwise, user may not even notice that no verification is performed.

Quick search for "fdm.conf" yields examples of configuration files that use TLS but don't enable certificate verification:
https://wiki.archlinux.org/index.php/fdm
https://gist.github.com/kgaughan/759186

**Comment by nicm** [comment]
This requires that people have installed a certificate bundle and I do
not want this to be a requirement.

**Comment by nicm** [comment]
Still, it would be nice to enable it by default. Perhaps an appropriate warning on error?

**Comment by jimcheetham** [comment]
I guess the argument is that "verifying" a certificate is more than just using TLS for opportunistic encryption, you also need to validate the certificate expiry and connection to a trusted root.

So if your existing "verify" option isn't checking the trusted state of a certificate, it isn't really verifying at all; it is still good to *use* TLS without verification in most circumstances.

I'd argue for making "verify-certificates" check in the CA store and validate fully (a change of function, and possibly needs a mechanism to locate the CA store explicitly as well), and perhaps add another option "encrypt-only-certificates" to match the current behaviour.
