### ISSUE TITLE
How to trigger (e.g.) notmuch for every incoming mail?

### ISSUE THREAD

**Issue by blackbit42** [nicm/fdm#144]
I am pretty sure there is no problem with fdm.
Though, I don't know how to solve a configuration challenge I have and wouldn't know where to ask besides here.
My config looks like this (simplified, redacted):
```
account "local" disabled maildir "%h/Maildir"
account "stdin" disabled stdin

match "^List-Id:.*mailman\\.example\\.org" in headers action maildir "%h/Maildir/.mailinglists.mailint-list-1"
match "^List-Id:.*mailman\\.example\\.net" in headers action maildir "%h/Maildir/.mailinglists.mailing-list-2"

match all action maildir "%h/Maildir"
```
For every email that comes in, regardless if moved into a mailing-list specific sub-maildir or not, should trigger an external program.
Something like `match all action exec "notmuch new"` but without influencing email delivery.
Any advice welcome.

**Comment by nicm** [comment]
Can't you just do pretty much that but with `continue` so it doesn't stop at that rule?

**Comment by blackbit42** [comment]
Hmm, we're getting there, but it's not working fully yet.

Let's contemplate the following config:
```
account "local" disabled maildir "%h/Maildir"
account "stdin" disabled stdin

match all action exec "notmuch new" continue

match "^List-Id:.*mailman\\.example\\.org" in headers action maildir "%h/Maildir/.mailinglists.mailint-list-1"
match "^List-Id:.*mailman\\.example\\.net" in headers action maildir "%h/Maildir/.mailinglists.mailing-list-2"

match all action maildir "%h/Maildir"
```
With this, mail delivery works as expected. Notmuch is triggered also, but the mail that triggered the fdm run isn't in the index yet. Notmuch runs before that email makes it to disk.

I have made another attempt also:
```
account "local" disabled maildir "%h/Maildir"
account "stdin" disabled stdin

match "^List-Id:.*mailman\\.example\\.org" in headers action maildir "%h/Maildir/.mailinglists.mailint-list-1" continue
match "^List-Id:.*mailman\\.example\\.net" in headers action maildir "%h/Maildir/.mailinglists.mailing-list-2" continue

match all action maildir "%h/Maildir" continue

match all action exec "notmuch new"
```

With this I get an email that belongs to a mailing list twice. Once in the respective sub-maildir and once in the main maildir.

I guess I am just too clumsy?

**Comment by nicm** [comment]
Easiest is probably to take your second config and make your `match all action maildir` rule `unmatched` instead of `all` so it doesn't match if either of the list rules match, although there are lots of other ways.

**Comment by blackbit42** [comment]
Yes, this seems to work.

What I have now is:
```
account "local" disabled maildir "%h/Maildir"
account "stdin" disabled stdin

match "^List-Id:.*mailman\\.example\\.org" in headers action maildir "%h/Maildir/.mailinglists.mailint-list-1" continue
match "^List-Id:.*mailman\\.example\\.net" in headers action maildir "%h/Maildir/.mailinglists.mailing-list-2" continue

match unmatched action maildir "%h/Maildir" continue

match all action exec "notmuch new"
```

Thank you!
