### ISSUE TITLE
Certificate fingerprint support

### ISSUE THREAD

**Issue by avkrotov** [nicm/fdm#15]
If server uses self-signed certificate, it is impossible to connect securely with fdm. There are two options to connect securely to the server that uses self-signed certificate: by adding CA to certificate bundle and by storing fingerprint (SSH-like trust on first use policy). The second option may be desirable when CA certificate is not available.

**Comment by nicm** [comment]
What are you asking here?

**Comment by jimcheetham** [comment]
It sounds like avkrotov is asking for a way to explicitly bless a self-signed certificate, without adding the certificate itself to the CA store. The usual way other projects do this is to allow a config line listing the public key directly, perhaps by pointing to the public key on disk, or directly including the (encoded) key directly

require-certificate filename | keydata
