### ISSUE TITLE
Using IMAP IDLE

### ISSUE THREAD

**Issue by jimcheetham** [nicm/fdm#18]
I'd like to be able to be able to connect to an IMAP source to collect email, and register for new mail events using the IDLE command. The same suggested daemon-mode could also periodically poll, for those servers that don't support IDLE, I suppose; both are 'better' than a loop outside fdm that keeps on re-invoking it, and leading to all that authentication being done again (also it means that I could use fdm to sensibly prompt for credentials, rather than leave them on disk somewhere)

If this something that could be done?

**Comment by nicm** [comment]
It would be a lot of work and there is not much chance of it
happening. fdm is not designed to stay connected to the server.

**Comment by jimcheetham** [comment]
That's a shame, but not completely unexpected. There's a lot of value for my workflow in having near real-time synchronisation (only one-way) between the central IMAP service and my local Maildirs, and I was hoping to be able to do it all within one tool, doing both the local inbound MTA role and the MDA.

However, if I have to use two or more tools then I have a lot of choice around how to get the work done. I will probably be able to use fdm as an MDA explicitly invoked by fetchmail or similar, replacing my existing Courier-MTA maildrop config, which is far messier than fdm for the same task.

**Comment by gehidore** [comment]
Checked issues to file the same request... shame it likely wont be implemented there isn't, that I can find, a quality mail fetching utility that I can find that supports IMAP IDLE and will still fetch all "new" mail regardless of read in another client or not.
