### ISSUE TITLE
SMTP - FROM & TO

### ISSUE THREAD

**Issue by strong99** [nicm/fdm#19]
I'm currently using the FDM as a relay between POP3 and SMTP (Postfix). My Postfix mailserver is currently rejecting all the received mail from FDM due to incorrect from and to e-mail headers. Once it receives the mail processed by FDM the addresses seem different:

Config:
```
action "tosmtp" smtp server "mail.mydomain.eu"
account "pop3" pop3 server "mail.source.eu" user <user> pass <pass>
match all action "tosmtp"
```

Mail:
```
FROM: user1@random.com
TO: user2@source.eu

```
Result at the mailserver "mail.mydomain.eu":
```
FROM: user1@mydomain.eu
TO: user2@mydomain.eu
```

If I add a forced "to" in the action, it gets delivered:
```
action "tosmtp" smtp server "mail.mydomain.eu" to "user2@source.eu"
```

The header information in the mailbox is (when "to" is set):
```
Return-Path: <user1@mydomain.eu>
Delivered-To: test-srv@mydomain.eu
Received: from mail.mydomain.eu (localhost [127.0.0.1])
       by mail.mydomain.eu (Postfix) with ESMTP id 74DDC1C1143
       for <test2@mydomain.eu>; Fri, 26 Aug 2016 15:05:33 +0200 (CEST)
...
From: <user1@random.com>
To: <user2@source.eu>
...
```

Postfix rejection, "/var/postfix/mail.log"
```
Aug 26 14:40:29 mydomain postfix/smtpd[5641]: connect from localhost[127.0.0.1]
Aug 26 14:40:29 mydomain postfix/smtpd[5641]: 709091C1143: client=localhost[127.0.0.1]
Aug 26 14:40:29 mydomain postfix/cleanup[5637]: 709091C1143: message-id=<000c01d1fd50$2dd24120$8976c360$@random.eu>
Aug 26 14:40:29 mydomain postfix/qmgr[4898]: 709091C1143: from=<user1@mydomain.eu>, size=4025, nrcpt=1 (queue active)
Aug 26 14:40:29 mydomain postfix/smtpd[5641]: disconnect from localhost[127.0.0.1]
Aug 26 14:40:29 mydomain amavis[1542]: (01542-03) Passed CLEAN {RelayedInternal}, MYNETS LOCAL [127.0.0.1]:44098 [77.171.48.199]  -> , Queue-ID: 1E66F1C1141, Message-ID: , mail_id: Ok1rTk5Ld4hm, Hits: 6.294, size: 3167, queued_as: 709091C1143, 333 ms, Tests: [DOS_OUTLOOK_TO_MX=1.449,FSL_HELO_NON_FQDN_1=0.001,HTML_MESSAGE=0.001,MIME_HTML_MOSTLY=0.001,RCVD_IN_PBL=3.558,RDNS_NONE=1.274,T_HEADER_FROM_DIFFERENT_DOMAINS=0.01]
Aug 26 14:40:29 mydomain postfix/local[5642]: 709091C1143: to=<user2@mydomain.eu>, relay=local, delay=0.03, delays=0.01/0.01/0/0.02, dsn=2.0.0, status=sent (delivered to mailbox)
```
The last line should have said: to = user2@source.eu, which works if "to" is set in the smtp action.

I've reviewed the code but to no avail.

Why and how are the FROM and TO headers manipulated?

**Comment by nicm** [comment]
fdm does not have the original envelope so it uses the local user and
host running fdm unless you specify it in the action ("to" and
"from").

If you want fdm to get the envelope from the mail headers, you may be
able to use a match regexp, tag the mail with the result, and use that
tag in the smtp server action.

But note that parsing From and To headers is nontrivial, you would be
much better to use the X-Envelope-To header if the original mail server
adds one.

Personally I would either set the "to" and "from" on the action, or try
to configure Postfix to understand your local user as an alias for your
actual destination account.
