### ISSUE TITLE
REGRESSION: IMAPS message count calculation incorrect

### ISSUE THREAD

**Issue by Megaboy5007** [nicm/fdm#22]
I am testing a setup involving a local server and an automatic fetch system, which I am fetching:
- Folder "INBOX" has 2 messages
- Folder "Sent" has 1 message

This totals 3 messages, and yet when I poll:
```
$ fdm poll
main: 5 messages found
```

I then added some extra lines in the config file to see if I could find the issue.
My current test ~/.fd.conf is now:
```
set no-received
set maximum-size 128M

$au = "foo"
$ap = "bar"
$as = "192.168.1.99"

account "main" imaps server "${as}" user "${au}" pass "${ap}" folders { "INBOX" "Sent" }

account "catchall" imaps server "${as}" user "${au}" pass "${ap}"
account "main-inbox" imaps server "${as}" user "${au}" pass "${ap}" folder "INBOX"
account "main-sent" imaps server "${as}" user "${au}" pass "${ap}" folder "Sent"

match all action pipe "/usr/local/libexec/dovecot/dovecot-lda -e"
```
The "catchall", "main-inbox", and "main-sent" accounts were added to see if it gets individual folders wrong.

When polling:
```
$ fdm poll
main-inbox: 2 messages found
main-sent: 1 messages found
catchall: 2 messages found
main: 5 messages found
```

If I delete just one message from the INBOX, the total reported is now 3. If I then delete the other message from the INBOX, the total reported is 1, which is correct (since it counted the message in the Sent folder).

fdm reports correctly with multiple messages when only one folder contains all the messages.

As per above, there are 3 messages to fetch from. On one run in a production system, it claims to have found 116 messages on the server, yet there were only around 30 when I checked and added up all messages in the folders. This occurs often, where the "messages found" is a number at least 3-5 times the actual number of messages present.

This bug appears to result in the "folders { ... }" syntax being unusable, as the program hangs after fetching just a few of the mails. Some sample output with 6 messages in the system (fdm poll reports 9):
```
...
main: message 6 delivered (rule 0, pipe) in 0.152 seconds
main: calling fetch state (0x7379e21a470, flags 0x00)
main: fetch, block
main: queued 1; blocked 0; flags 0x00
parent: 2 children, 5 dead children
main: polling: 2, timeout=0
main: fetch loop start
main: trying (deliver) message 6
main: deliver message 6, match
parent: child 1105 socket error
main: calling fetch state (0x7379e21a470, flags 0x00)
main: fetch, block
main: queued 1; blocked 0; flags 0x00
main: polling: 2, timeout=0
parent: 2 children, 5 dead children
main: fetch loop start
main: trying (match) message 6
main: match message 6, done
main: deleting message 6
main: calling fetch state (0x7379e21a470, flags 0x02)
main: fetch, block
main: queued 0; blocked 0; flags 0x02
main: polling: 2, timeout=900000
main: fetch loop start
main: calling fetch state (0x7379e219800, flags 0x02)
main: fetch, block
main: queued 0; blocked 0; flags 0x02
main: polling: 2, timeout=900000
parent: waiting for children
parent: child 1105 returned 0
parent: waiting for children
parent: 1 children, 6 dead children
main: fetch loop start
main: calling fetch state (0x7379e219800, flags 0x02)
main: fetch, again
main: fetch loop start
main: calling fetch state (0x7379e21a470, flags 0x02)
main: fetch, block
main: queued 0; blocked 0; flags 0x02
main: polling: 2, timeout=900000
```
It hangs at the very end, and 'top' reveals that two fdm processes are present, stuck on WAIT state "poll".

Using OpenBSD 5.9 (GENERIC.MP), with fdm-1.9 package (pkg_add). This appears to be a regression that was once fixed in 2009, according to the CHANGES file.

**Comment by nicm** [comment]
Show me the full -vvvv log for poll of one account please.

**Comment by Megaboy5007** [comment]
Hello Nicholas,

I have created a fresh install with OpenBSD -current (22/10/16), using dovecot as the mail server and fdm pointed to 127.0.0.1. Added two folders with 10 messages in each (total 20 messages). `fdm poll` reports 30.

**Comment by nicm** [comment]
Log?

**Comment by nicm** [comment]
Show me the -vvvv log for polling one account please.

**Comment by Megaboy5007** [comment]
Hi Nicholas,
I attached the logs in the previous comment. Is there a separate file that fdm logs to?
Can you not access the attached text files or am I missing something?

**Comment by nicm** [comment]
Sorry GitHub doesn't send another email if you edit the message.

Please apply this, rebuild then show me the same log from fdm -vvvv poll (just the poll log): [x.txt](https://github.com/nicm/fdm/files/552895/x.txt)

**Comment by nicm** [comment]
Just the poll log with all stderr, stdout, everything, I don't need separate logs.

**Comment by Megaboy5007** [comment]
[Patched fdm -vvvv poll log](https://github.com/nicm/fdm/files/552976/polldbg.txt)

**Comment by nicm** [comment]
Try this please: 
[y.txt](https://github.com/nicm/fdm/files/553043/y.txt)

**Comment by Megaboy5007** [comment]
The y.txt patch works with poll now, but fetch still hangs unless all the messages are in a single folder, perhaps there is another underlying issue leading to this in the first place?

Logs (both x and y patches applied; note I killed the process, which shows in the fetch log):
[fdm -vvvv poll log](https://github.com/nicm/fdm/files/553092/polldbg.txt)
[fdm -vvvv fetch log](https://github.com/nicm/fdm/files/553097/fetchdbg.txt)

Same as above, but all 20 messages in INBOX (ie. all messages to be polled/fetched in a single folder):
[fvm -vvvv poll log](https://github.com/nicm/fdm/files/553106/pollsingle.txt)
[fvm -vvvv fetch log](https://github.com/nicm/fdm/files/553108/fetchsingle.txt)

**Comment by nicm** [comment]
Try this instead please 
[z.txt](https://github.com/nicm/fdm/files/553337/z.txt)

**Comment by Megaboy5007** [comment]
Patch "z.txt" works well. `fdm poll` reports the correct number of messages, and `fdm fetch` no longer hangs at the end.

**Comment by nicm** [comment]
I have applied this now, thanks.
