### ISSUE TITLE
dispaly  delivered directory name in verbose

### ISSUE THREAD

**Issue by rkanavath** [nicm/fdm#27]
I have message like below from fdm -v -k
msg: got message 2 of 2: size 994, body 973
msg: message 2 delivered (rule 82, maildir) in 0.019 seconds

How do i find whicg maidir directory this mail was delivered. I had a lot of filters in my fdm.conf

for example

...
$ubuntu = "${path}/Ubuntu"
...
action "ubuntu"     maildir "${ubuntu}/News"
...

now if fdm fetch a mail from sever that matches exactly ubuntu/News. How do I know that information in verbose.? Is there already an option for that?

**Comment by nicm** [comment]
It should tell you which rule it was then you can match it up with the
rule list at the start to see where it went.

**Comment by nicm** [comment]
Also if you add more -v it will show where it is writing the file.

**Comment by rkanavath** [comment]
Thanks.

fdm -kvv fetch says where the file is written. I wish it says

fdm -kv fetch 
msg: message 2 delivered (rule 82, maildir/Inbox ) in 0.019 seconds
