### ISSUE TITLE
regex for chinese only subjects (working with grep -G, not with fdm)

### ISSUE THREAD

**Issue by Siltaar** [nicm/fdm#35]
Hi,

I tried this config to trash chinese spam in a non-chinese mailbox :
```
account "a" maildir "~/.Maildir/
match not "^Subject: .*[a-zA-Z0-9[:punct:]]" in headers action maildir "%h/.Maildir/.spam"       
match all action keep
```

With grep it works like a cham:
```
$ echo "Subject: 家有小奴各种制服来诱 惑" | grep -G "^Subject: .*[a-zA-Z0-9[:punct:]]"
$
$ echo "Subject: 家有小奴各种制服来诱 惑à" | grep -G "^Subject: .*[a-zA-Z0-9[:punct:]]"
Subject: 家有小奴各种制服来诱 惑à
$
```

With FDM the message is kept in the inbox (when I apply the rule with the previous config as a filter), and worse, one legit message is spamed (among around a hundred others which are kept as expected):
```Subject: Urssaf en ligne : Confirmation de votre adresse courriel```

Here are some relevant -vvvv log line about the false positiv if it can help:
```
parent: 1 children, 2 dead children
a: reading mail from: /home/<user>/.Maildir//new/1489354359.6840_5.tabr
a: read 3903 bytes
a: fetch, mail   
a: found 73 lines, 33 in body
a: message-id is: <201602231711.u1NHBgwJ008124@palerme.declaration.urssaf.fr>
a: found 20 wrapped lines
a: got message 69: size 3978, body 1887
a: fetch loop start
a: trying (match) message 69
a: matching from 0 to 1887 (size=3978, body=1887)
a: tried regexp "^Subject: .*[a-zA-Z0-9[:punct:]]" in headers, result now 1
a: finished rule 0, result 1
a: matched to rule 0
a: action <rule 0>:0 (maildir), user <user>
a: match message 69, deliver
a: trying (deliver) message 68
a: deliver message 68, blocked
a: trying (deliver) message 69
a: message 69, running action <rule 0>:0 (maildir) as user <user>
a: sending action to parent
a: deliver message 69, blocked
a: queued 2; blocked 2; flags 0x00
a: polling: 1, timeout=900000
parent: got message type 0, id 69 from child 8563
parent: deliver child 8566 started (uid 1000)
parent: 2 children, 2 dead children
```

**Comment by nicm** [comment]
Does it do the same with grep -E?

**Comment by Siltaar** [comment]
Exactly.
Which on (grep -E or grep -G) is behaving like the C regexp provided by regex.h ?

**Comment by nicm** [comment]
-E

Please give me two files with one of the false positives and one of the
false negatives.



On 13 Mar 2017 9:59 am, "Simon Descarpentries" <notifications@github.com>
wrote:

Exactly.
Which on (grep -E or grep -G) is behaving like the C regexp provided by
regex.h ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nicm/fdm/issues/35#issuecomment-286062743>, or mute the
thread

**Comment by Siltaar** [comment]
Here is the false positive:
Return-Path: <teledep@palerme.declaration.urssaf.fr>
Delivered-To: user@domaine.fr
Received: by tabr (fdm 1.7, account "a");
        Sun, 12 Mar 2017 21:47:15 +0000
Received: by tabr (fdm 1.7, account "usr@domaine");
        Tue, 23 Feb 2016 18:14:02 +0100
Received: from other-dom.com (other-dom.com [92.243.17.214])
        (using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
        (No client certificate requested)
        by machine.globenet.org (Postfix) with ESMTPS id 58FAF763D8
        for <user@domaine.fr>; Tue, 23 Feb 2016 18:11:43 +0100 (CET)
Received: from palerme.declaration.urssaf.fr ([194.0.166.4])
        by other-dom.com with esmtp (Exim 4.86)
        (envelope-from <teledep@palerme.declaration.urssaf.fr>)
        id 1aYGS9-000744-Vx
        for contact@acoeuro.com; Tue, 23 Feb 2016 18:08:50 +0100
Received: from palerme.declaration.urssaf.fr (localhost.localdomain [127.0.0.1])
        by palerme.declaration.urssaf.fr (8.14.4/8.14.4) with ESMTP id u1NHBgOM008125
        for <contact@other-dom.com>; Tue, 23 Feb 2016 18:11:42 +0100
Received: (from teledep@localhost)
        by palerme.declaration.urssaf.fr (8.14.4/8.13.1/Submit) id u1NHBgwJ008124
        for contact@other-dom.com; Tue, 23 Feb 2016 18:11:42 +0100
Date: Tue, 23 Feb 2016 18:11:42 +0100
Message-Id: <201602231711.u1NHBgwJ008124@palerme.declaration.urssaf.fr>
From: teledep@declaration.urssaf.fr
To: contact@other-dom.com
Subject: Urssaf en ligne : Confirmation de votre adresse courriel
MIME-Version: 1.0
Content-Type: multipart/alternative;
        boundary="----=_NextPart_000_0011_01CC94B2.C3AEBCC0"
Content-Length: 2091

Content-Type: text/html;
        charset="iso-8859-1"
Content-Transfer-Encoding: 8bit

[-- Visualisation automatique en utilisant lynx -dump -force_html -width=96 ''/tmp/muttse8Pv5''
--]
   L'Urssaf a bien enregistré votre adresse courriel et vous prie de bien vouloir la
   confirmer en
   cliquant sur le lien suivant:[1] « Confirmer mon adresse courriel ».
   Pour toute information, nous vous invitons à vous rapprocher de votre conseiller Urssaf
   0811 011 637 (prix d'un appel local).
   Merci de ne pas répondre à ce message qui est généré automatiquement.

Références

   1. https://mon.urssaf.fr/mail/confirmation?rEcasB9+IDV4hqM/zWz9SRtMqJ8ZuFwygWu+UY83EpeQGndOqdI
mC52TR3RWyXb1ib9AZZplChfDZMIpHXmj872Q613CZBsWYLn7VqRMUGV+J8bDIh7Eh7wQNY1MoSgMbfZEqQpXZpxwI8Q4IL/i
izhhtg/zadZau75LJLnAwww/tVtBxQ9PjBwcYxMD5Gy/I/rvE/ZZeonCTv52i6Bu5EYdImR9atJHfZzS9Qm2KGFWBGsHnBNes
HfccITTBsK3SA+r8F1PrqiN25YOZGxAQhInNfKnqxY/u2Vsd2HRA3Br5PrnO+DDCfHLnkxjqlU8jyxBi6W2Y5wyXGJQKDPvpS
x33VFrmPGauWMN7ZvaUZdM/cjlMRe/a7GFfJdNmqqR,1

**Comment by Siltaar** [comment]
Here is a missed spam:

```
Return-Path: <ZYX2546@scc4.cn>
Delivered-To: user@dom1.work
Received: by tabr (fdm 1.7, account "a");
        Sun, 12 Mar 2017 17:34:53 +0000
Received: by tabr (fdm 1.7, account "usr@gandi");
        Sun, 12 Mar 2017 17:49:01 +0100
Received: from spool.mail.gandi.net (mspool4-d.mgt.gandi.net [10.0.21.135])
        by nmboxes66.sd2.0x35.net (Postfix) with ESMTP id 835F828878
        for <user@dom1.work>; Sun, 12 Mar 2017 17:45:07 +0100 (CET)
Received: from acoeuro.com (unknown [IPv6:2001:4b98:dc0:43:216:3eff:febf:d9a6])
        by spool.mail.gandi.net (Postfix) with ESMTPS id 3171914203D
        for <user@dom1.work>; Sun, 12 Mar 2017 17:45:04 +0100 (CET)
Received: from [116.236.180.116] (helo=sc4c-mail-01.sc4c.scg.local)
        by other-dom.com with esmtp (Exim 4.87)
        (envelope-from <ZYX2546@scc4.cn>)
        id 1cn6cC-0000FC-U8
        for contact@other-dom.com; Sun, 12 Mar 2017 17:45:05 +0100
Received: from kif (223.152.83.77) by sc4c-mail-01.sc4c.scg.local (10.6.0.5)
        with Microsoft SMTP Server id 8.2.255.0; Sun, 12 Mar 2017 13:55:29 +0800
Message-ID: <14A96022F639F463638A767BA3302080@kif>
From: gfvezwl <zyx2546@scc4.cn>
To: group64028@xiaoi.com, contact@other-dom.com, affiliate@dafa888.com
Subject: 家有小奴各种制服来诱惑
Date: Sun, 12 Mar 2017 14:57:29 +0800
MIME-Version: 1.0
Content-Type: text/html; charset="gb2312"
Content-Transfer-Encoding: base64
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2900.5512
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.5512
X-Spamd-Result: default: False [9.20 / 30.00]
        FORGED_OUTLOOK_HTML(5.00)[]
        HFILTER_HOSTNAME_UNKNOWN(2.50)[]
        AUTH_NA(1.00)[]
        R_DKIM_NA(0.00)[]
        MIME_HTML_ONLY(0.20)[]
        TO_DN_NONE(0.00)[]
        R_SPF_NA(0.00)[]
        RCPT_COUNT_21(0.00)[]
        RCVD_COUNT_4(0.00)[]
        FROM_HAS_DN(0.00)[]
        HAS_X_PRIO_3(0.00)[]
        DMARC_NA(0.00)[scc4.cn]
        MID_RHS_NOT_FQDN(0.50)[]
        FROM_EQ_ENVFROM(0.00)[]
X-Rspamd-Server: nmfilter4.prod.sd2.0x35.net
X-Rspamd-Scan-Time: 1.28
X-Rspamd-Queue-ID: 3171914203D
X-Spam-Level: *********
X-Spam-Flag: yes
Content-Length: 922

[-- Visualisation automatique en utilisant lynx -dump -force_html -width=96 ''/tmp/muttglD3QR''
--]
                            [1]http://sxwbank.cn/

       26579846

Références

   1. http://sxwbank.cn/
```

**Comment by nicm** [comment]
Please upload these as text files instead of pasting them...

**Comment by Siltaar** [comment]
This is strange about the false positive:
` Content-Transfer-Encoding: 8bit`

**Comment by Siltaar** [comment]
I edited my previous posts to upload text files instead.

**Comment by nicm** [comment]
This one matches:

$ egrep "^Subject: .*[a-zA-Z0-9[:punct:]]" chinese.txt
Subject: =?gb2312?B?vNLT0NChxau499bW1sa3/sC009W78w==?=

**Comment by nicm** [comment]
And this one does not, because it is missing a space after Subject:

$ egrep ^Subject: urssaf.txt
Subject:Urssaf en ligne : Confirmation de votre adresse courriel

**Comment by nicm** [comment]
Something like 

~~~~
^Subject: *=\?.*\?[BQ]\?
~~~~

Would probably block all non-ASCII subjects but note that that might block people who use letters like é. YMMV.

https://ncona.com/2011/06/using-utf-8-characters-on-an-e-mail-subject/ has a short explanation of how the subject line is encoded.

**Comment by Siltaar** [comment]
Ok, so I made a script to get the relevant information, but I found no example of how to properly write a pipe clause : 
`match pipe "unicode_subject.py" returns "^[^a-zA-Z0-9[:punct:]]*$" action maildir "%h/.Maildir/.spam" `

I get : `.fdm.filtre: syntax error at line 15` (the previously copied line)

**Comment by nicm** [comment]
match pipe "myprogram" returns (, "failed") actions { "act1" "act2" }

**Comment by Siltaar** [comment]
Hi,

Thanks a lot for this hint. I succeeded in getting it working, with the given (updated) Python script to decode subject headers.

I got things clear here : https://github.com/Siltaar/unicode_subject if anyone else get interested in this working trick.
