### ISSUE TITLE
Tagging and regexp capturing brackets

### ISSUE THREAD

**Issue by Siltaar** [nicm/fdm#37]
Hi,

So I made a script and try to get its result with FDM:
```
match pipe "python3 -sqI /home/siltaar/.sbin/spam_test.py" returns (,'^(drop|keep)$') action tag "%0" continue
match tagged "keep" action maildir "%h/.Maildir/.spam"
match tagged "drop" action drop
```
But nothing seems to get tagged… Am I missing something obvious ?
(my script returns "drop" for spam to drop, "keep" for spam to investigate, or nothing for not spam, and I need these 3 states…).

**Comment by Siltaar** [comment]
%[command1] in this file : https://github.com/nicm/fdm/blob/master/examples/f-terbeck.conf
looks undocumented…

**Comment by Siltaar** [comment]
> %0 to %9 are replaced
>      with the result of any bracket expressions in the last regexp.

Must be excluding pipe result regexp…

**Comment by Siltaar** [comment]
Hum interesting:
> kernel: [7347438.783523] fdm[18662]: segfault at fffffffff0d49650 ip
> 0000003000481e14 sp 00007ffeef4d3d18 error 5 in libc-2.19.so[3000400000+1a1000]

**Comment by Siltaar** [comment]
Like this it works :
```
match pipe "python3 -sqI /home/siltaar/.sbin/spam_test.py" returns (,'keep') action maildir "%h/.Maildir/.spam"
match pipe "python3 -sqI /home/siltaar/.sbin/spam_test.py" returns (,'drop') action drop
```
But it takes twice as long as it should…

**Comment by Siltaar** [comment]
A rewrite version needs to parse the whole email, which is slow…
```
match all action rewrite "python3 -sqI /home/siltaar/.sbin/spam_test_rewrite.py" continue
match "^X-Siltaar-Spam-Score: 1$" in headers action maildir "%h/.Maildir/.spam"
match "^X-Siltaar-Spam-Score: 2$" in headers action maildir "%h/.Maildir/.furspam"
```
170ms by email (for 70 emails in the test), against 195ms by email with the double headers-only parsing of previous comment.
I was around 60ms when dealing only with the subject, as matter of comparison.

**Comment by Siltaar** [comment]
150ms by email with Python2.7 (instead of 3.4)
Cython compilation is not improving this task.

**Comment by Siltaar** [comment]
125ms by email if parsing headers only…
Here is my script : https://github.com/Siltaar/spam_test_rewrite
There are currently 2 sets of rules, each one is able to increment the spam score by 1.
- If the subject is missing, empty or contains less than half alphabetical letters, the spam score is incremented by 1.
- If there is no recipient or more than 9, the spam score is incremented by 1.

**Comment by nicm** [comment]
Do you still have an issue? I'm not sure what you are asking.

**Comment by Siltaar** [comment]
1 - With the config file sample of the 1st port, why does the `%0` to `%9` substitution strings (for regexp capturing brackets) are not working ?

2 - Then, in the second post, I show an extract from the pointed example config file, which looks like undocumented.

3 - Playing with those settings I had FDM segfaulting, it might have interest you.

**Comment by nicm** [comment]
They end up in tags command0, command1 etc not %0, %1 etc. MANUAL:

~~~~
Note that %0 to %9 are used only for 'regexp' rules. Regexps that are part of
'command' rules use the 'command0' to 'command9' tags.
~~~

I'm not that interested in segfault unless you can send me an easy way to reproduce.

**Comment by Siltaar** [comment]
So the two first points were linked.

It's interesting to note that the current Debian stable fdm.conf manpage is anterior to this commit:
https://github.com/nicm/fdm/commit/99601862d648b4cef4904d4e4a3aee42310554d8 so…
It dates from august 2006.

Thanks for the hint.
