### ISSUE TITLE
Sync local changes back to server

### ISSUE THREAD

**Issue by dave-kennedy** [nicm/fdm#38]
I have an Outlook email address that works very slowly over IMAP. It's
practically unusable with Mutt's IMAP feature.

It works much better if I fetch the emails with fdm and use Mutt to manage
them locally. The problem with that, however, is any operations performed on
the emails - such as deleting or moving them to another folder - aren't synced
with the server. Then, when I use Mutt on another computer with the same
account, I have to do it all over again.

Can fdm sync local changes back to the IMAP server so the folders will be
mirrored?

**Comment by nicm** [comment]
No fdm is a mail fetch program it is not designed to sync IMAP.

**Comment by ra1fh** [comment]
For me http://isync.sourceforge.net/ works well for this. I use isync to synchronize to a local maildir and then run fdm locally for some filtering into separate folders. Changes to the synchronized folders would be reflected back to the server on the next isync run.

There is also http://www.offlineimap.org/ that does the same thing (I actually used that before but found isync to be more stable).

The actual reason for this setup is not so much mutt/imap slowness, but $COMPANY thinks IMAP is insecure and has disabled it. So I put isync and  http://davmail.sourceforge.net/ in front of Exchange and can still use mutt to read email in addition to Outlook (where necessary).

**Comment by dave-kennedy** [comment]
Nice, thanks for the tip!
