### ISSUE TITLE
Unable to build latest revision on OpenBSD 6.1

### ISSUE THREAD

**Issue by Megaboy5007** [nicm/fdm#39]
In the latest revision (cae4ea37b6b296d1b2e48f62934ea3a7f6085e33) I cannot run configure on OpenBSD 6.1.

$ automake-1.15
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/local/bin/automake-1.15 line 3936.
Provide an AUTOCONF_VERSION environment variable, please
automake-1.15: error: autoconf failed with exit status: 127
$ autoconf-2.69
configure.ac:8: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:18: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:30: error: possibly undefined macro: AM_CONDITIONAL
$ ./configure
configure: error: cannot find install-sh, install.sh, or shtool in etc "."/etc

What am I doing wrong? This worked flawlessly on OpenBSD 5.9/6.0, but has stopped working as of 6.1.

**Comment by nicm** [comment]
What happens when you run autogen.sh?

**Comment by Megaboy5007** [comment]
Thanks Nick, that works.

However, note this is the output:

$ autogen.sh
main::scan_file() called too early to check prototype at /usr/local/bin/aclocal-1.10 line 617.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/local/bin/automake-1.10 line 3832.
configure.ac:19: installing `etc/compile'
configure.ac:11: installing `etc/config.guess'
configure.ac:11: installing `etc/config.sub'
configure.ac:8: installing `etc/install-sh'
configure.ac:8: installing `etc/missing'
Makefile.am: installing `etc/depcomp'
configure.ac: installing `etc/ylwrap'
main::scan_file() called too early to check prototype at /usr/local/bin/aclocal-1.10 line 617.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/local/bin/automake-1.10 line 3832.

Also, while building is successful, this warning may want some attention:

$ make -s -j 4
updating parse.h
file.o: In function `locksleep':
file.c:(.text+0x5ae): warning: warning: random() may return deterministic values, is that what you want?

I think the build process here could be documented better, as there are no source tarballs available from the official site (so it seems). Especially important given that there are several versions of autoconf/automake avaialable in the OpenBSD package repository.

**Comment by nicm** [comment]
There are source tarballs for every release.

**Comment by Megaboy5007** [comment]
My bad, there are tarballs, for releases anyway. However, the last release (1.9) has a major show-stopper that prevents IMAP from working with multiple folders, which is fixed in the last commit, hence why I have to build from the github repo. ;)
