### ISSUE TITLE
Can't connect to google apps account using IMAP

### ISSUE THREAD

**Issue by fedemp** [nicm/fdm#5]
Trying `fdm` on archlinux, but I can't get my mail through IMAP. This is my .fdm.conf

    action "inbox" maildir "%h/Mail/INBOX"
    account "mycompany" imaps server "imap.gmail.com" port 993 user "me@mycompany.com" pass
    "password"
    match all action "inbox"

When I try `fdm -kv fetch` I get this error:

    unexpected data: 2 NO [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)

IMAP is enabled on the account.

**Comment by nicm** [comment]
This does not seem like a problem with fdm.

**Comment by fedemp** [comment]
Ok. Surely it's not a bug, but since Google didn't help at all and the mailing list seems to be dead by now, this is the only place where I could find somebody who cares. If there's a better place I could ask this, I would be pleased to know.

The configuration file isn't that hard to create as to assume that I have done something wrong, but since I may be doing something wrong, it would be great to determine what it is so more potential users don't uninstall just because "it doesn't work".

**Comment by nicm** [comment]
I use Google IMAP daily so you must have something misconfigured

**Comment by fedemp** [comment]
In case somebody else finds this issue and has the same problem, you have to enable "access to less secure apps" in Gmail.

https://www.google.com/settings/security/lesssecureapps

**Comment by fedemp** [comment]
In case somebody else finds this issue and has the same problem, you have to enable "access to less secure apps" in Gmail.

https://www.google.com/settings/security/lesssecureapps

**Comment by fedemp** [comment]
In case somebody else finds this issue and has the same problem, you have to enable "access to less secure apps" in Gmail.

https://www.google.com/settings/security/lesssecureapps
