### ISSUE TITLE
How to debug error with google account?

### ISSUE THREAD

**Issue by vp1981** [nicm/fdm#62]
Hello,
I configured fdm for two google accounts and one of them works fine (i.e. obvious without error) while the other one gives error:
```
gm-list: unexpected data: -ERR [AUTH] Username and password not accepted.
```

I have following in `~/.fdm.conf`:
```
account "gm-list"   pop3s server "pop.gmail.com" port 995 user "lomov.vl"       pass "PASSWORD"   new-only cache $db + "-gl" keep
account "gm-sci"    pop3s server "pop.gmail.com" port 995 user "v.p.lomov"      pass "PASSWORD"   new-only cache $db + "-gs" keep
```

P.S. As I figured out `account`s have to have different cache files when 'fcntl' lock-types is used, because other way I get "Bad file descriptor".

**Comment by nicm** [comment]
-vvvv will show everything fdm is sending and receiving from the server.

**Comment by vp1981** [comment]
Thank you Nicholas.

I see more details, but didn't understand the reason of -ERR [AUTH]. It goes right after > PASS ..... I suspect that there may be problem with some characters in a password (on the other hand, I could log in using Web interface). The PASSWORD is enclosed in double quotes in `~/.fdm.conf` but is it possible that I need to escape also other characters than '"' and '\\'?

The other google account works fine and difference between passwords is that not-working has "'" (single quote), '$' ("dollar sign") and '%' ("percent sign"). In PASS string the password is the same as in `~/.fdm.conf` file.

**Comment by nicm** [comment]
Did you try putting the password in an netrc file instead of fdm.conf? The
parsers are different.

**Comment by vp1981** [comment]
Thank you Nicholas!

That works! I didn't thought would give different. From MANUAL it is unclear when to use `~/.netrc`, is it more preferable than the passwords in `~/.fdm.conf` (and may be using `include` command), also I'm not sure how to escape characters in `~/.netrc`.
