### ISSUE TITLE
Use variables in commands

### ISSUE THREAD

**Issue by lahwaacz** [nicm/fdm#64]
Using variables in commands should be supported. I've tried both
```
$my_password = $(gpg --quiet --batch --use-agent --decrypt --output - "%h/path/to/my/password.gpg")
```
and
```
$my_password_file = "%h/path/to/my/password.gpg"
$my_password = $(gpg --quiet --batch --use-agent --decrypt --output - ${my_password_file})
```
but both result in the string being interpreted literally as a command.

**Comment by nicm** [comment]
= doesn't expand %s so the first and the first line of the second won't work.

The second should replace ${my_password_file} though.

This might be enough to make it expand %s:
~~~~
--- a/parse.y
+++ b/parse.y
@@ -749,7 +749,7 @@ set: TOKSET TOKMAXSIZE size
             conf.file_umask = n;
      }

-defmacro: STRMACRO '=' strv
+defmacro: STRMACRO '=' replstrv
          {
                  struct macro  *macro;

**Comment by lahwaacz** [comment]
If I try:
```
$str = "something"
$output = $(echo a/${str}/b > log)
```
Then the log contains just `a//b` so `${str}` wasn't replaced with `something`.

**Comment by lahwaacz** [comment]
Was this fixed?

**Comment by lahwaacz** [comment]
ping
