### ISSUE TITLE
Please add a --dry-run option

### ISSUE THREAD

**Issue by blackbit42** [nicm/fdm#67]
It would be useful to have a --dry-run option to be able to validate that a rule-set is performing the intended action without actually altering a mailspool.
For every triggered match a  message should be printed, stating what would happen if fdm is run without --dry-run.

**Comment by nicm** [comment]
You mean like -n?

**Comment by blackbit42** [comment]
Not quite.
-n verifies that the config file can be parsed, but doesn't tough any emails.
I would like the mailbox(es) to be opened, the rules to be evaluated but instead of the actual actions to be executed, just an output what _would_ happen with the emails.

**Comment by nicm** [comment]
OK, fair enough. I'm not really working on fdm much anymore so unless you do it, this is unlikely to happen.
