### ISSUE TITLE
can i avoid storing passwords in plain text?

### ISSUE THREAD

**Issue by daphniz** [nicm/fdm#72]
is there no way to avoid storing passwords in plain text?

**Comment by iamleot** [comment]
Hello D,

D writes:
> is there no way to avoid storing passwords in plain text?

Yes, you can use $(...) in the configuration file, e.g.

 pass $(pass show email.example.org | head -1)

(and that will use the output of `pass show ... | head -1' as password.)

**Comment by daphniz** [comment]
thanks, iamleot!  it seems to work without head -1 as well.
