### ISSUE TITLE
Split multiple accounts into their own folder

### ISSUE THREAD

**Issue by balljointedmae** [nicm/fdm#75]
Howdy! I'm trying to figure out how to split multiple accounts into their own folders on maildir like mail/riseup and mail/countermail.

**Comment by nicm** [comment]
%[account] tag will tell you which account a mail was fetched from.

**Comment by gigavinyl** [comment]
Awesome! I'm using actions to move things to folders, do I just repeat this for each account?

**Comment by gigavinyl** [comment]
```# General.                                                                                                                                                                                                        action "inbox"      maildir "${path}/%[account]/Inbox"
action "junk"       maildir "${path}/%[account]/Junk"
action "sent"       maildir "${path}/%[account]/Sent"
action "spam"       maildir "${path}/%[account]/Spam"
```
like so

**Comment by nicm** [comment]
You should be able to use the tag in the folder name if you want the
account name in the folder name.

**Comment by nicm** [comment]
Oh yes. There might be a tag for the action name too if you wanted to use
it, I can't remember.

**Comment by nicm** [comment]
You will need a match statement also of course.

**Comment by gigavinyl** [comment]
I see thanks!

Now I'm getting an authentication error though even thought I know my username and password are right.

**Comment by gigavinyl** [comment]
The error is:
```
riseup: unexpected data: 220 bell.riseup.net ESMTP (spam is not appreciated)
riseup: fetching error. aborted
```

**Comment by nicm** [comment]
Did you get this sorted out?
