### ISSUE TITLE
Uninformative logging when smtp action lacks optional 'to'

### ISSUE THREAD

**Issue by aaletal** [nicm/fdm#78]
With:
action "localdelivery" smtp server "localhost"
in ~/.fdm.conf and match all action "localdelivery", crontab -l == */12 * * * * /usr/local/bin/fdm fetch >/dev/null, logs fill up with:
datestamp hostname fdm: vfprintf %s NULL in "smtp%s server "%s" port %s to "%s""

This can be traced to deliver_smtp.c lines 235-237, function deliver_smtp_desc:

xsnprintf(buf, len, "smtp%s server \"%s\" port %s to \"%s\"",
    data->server.ssl ? "s" : "", data->server.host, data->server.port,
    data->to.str);

Modifying .fdm.conf to specify 'to "username@host.domain"' avoids the null pointer. At a guess, it can also be avoided by modifying line 237 to data->to ? data.to.str : "" or something. Possibly it needs two different invocations, checking whether the optional to has been initialized. Possibly instead the default to should get initialized before invocation. Sorry that I can't be clearer, but it should be easily reproducible by setting up the action and rule above, with a target to pull from as well (without deleting from server, while testing (umm, sorry, you know these things, I'm sure)), and viewing logs. It's not a big deal, mostly cosmetic in logs, but getting log-splattered is always at least mildly annoying.

**Comment by nicm** [comment]
Changed now, thanks!
