### ISSUE TITLE
Option to unwrap wrapped lines at 76 characters when saved in maildir

### ISSUE THREAD

**Issue by balki** [nicm/fdm#82]
When emails are saved in maildirs, the text file is wrapped at 76 characters. Since the wrap could break between words, it affects searching for keywords across emails. An option to unwrap automatically for text like content types would be helpful.

**Comment by nicm** [comment]
fdm does not wrap lines at 76 characters, probably the original mail was wrapped at 76 characters.

**Comment by balki** [comment]
Yes. it is the original mail. But most (if not all) mail are wrapped as that is the format from RFC.

**Comment by balki** [comment]
@nicm Do you think it is a good idea to have an option for this? Would you accept a pull request?

**Comment by nicm** [comment]
Why don't you pass the mail through a rewrite rule first to unwrap it?

**Comment by balki** [comment]
Thank. I will try with rewrite rule.
