### ISSUE TITLE
Broken prototypes for base64 functions

### ISSUE THREAD

**Issue by ismaell** [nicm/fdm#92]
Following two prototypes at `fdm.h` are incorrect:
```C
int b64_ntop(src, srclength, target, targsize);
int b64_pton(src, target, targsize);
```

**Comment by nicm** [comment]
This is already fixed in 3232e537.

**Comment by ismaell** [comment]
Yes, sorry, I meant they were broken on release 2.0.0.

**Comment by nicm** [comment]
OK, they will be fixed in the next release :-).

**Comment by nicm** [comment]
I don't know, I am not working on fdm much anymore.

**Comment by nicm** [comment]
I should look and see if there are enough changes to warrant another release...

**Comment by ismaell** [comment]
Better one with few changes than none at all :-).
