### ISSUE TITLE
fsync unhappines over NFS

### ISSUE THREAD

**Issue by ttw** [nicm/fdm#93]
Only had a quick look so cannot say too much but (even though I'm not convinced about the usefulness of 'fsync' before a 'close' as ?the latter implies the former?) I defer to previous note in CHANGES file regarding the need for 'fflush'.  Certainly, the attached APPEARS to resolve my issue.  May also be an issue with 'Operating System / libc' or 'Operating System / NFS'.

[nicm+fdm+deliver-maildir-c.patch.gz](https://github.com/nicm/fdm/files/6071516/nicm%2Bfdm%2Bdeliver-maildir-c.patch.gz)

**Comment by nicm** [comment]
fflush is for stdio, this code is using write which does not go through stdio.

close does not necessarily imply fsync, the kernel may defer it.

**Comment by nicm** [comment]
I am surprised this doesn't crash for you, because fflush takes a FILE* pointer not a file descriptor. Are you sure you are actually using an fdm built with this change? And that it is going through this code path?

**Comment by ttw** [comment]
You're right.  It wasn't executing the code path; my cron job ran just before my test and it was running against an empty source.  Apologies (and thank you for the education on 'close' returning with deferred writes).  I'll have to break out those checks to double check that it's the 'fsync'.  It's intermittent so, will see.

**Comment by ttw** [comment]
Thought I had better opportunity to replicate this (was seeing regular errors when posted originally) but seems stable now that I've rebuilt from 'master'; only delta is a couple of basic 'log_debug' lines to verify that it was the 'fsync' causing the error.  Closing as a ghost issue; apologies for the noise.
